/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivewearRouteImport } from './routes/activewear'
import { Route as CasualWearRouteImport } from './routes/casual-wear'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as SportswearRouteImport } from './routes/sportswear'
import { Route as TrackRouteImport } from './routes/track'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivewearRoute = ActivewearRouteImport.update({
  id: '/activewear',
  path: '/activewear',
  getParentRoute: () => rootRouteImport,
} as any)
const CasualWearRoute = CasualWearRouteImport.update({
  id: '/casual-wear',
  path: '/casual-wear',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const SportswearRoute = SportswearRouteImport.update({
  id: '/sportswear',
  path: '/sportswear',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activewear': typeof ActivewearRoute
  '/casual-wear': typeof CasualWearRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/quote': typeof QuoteRoute
  '/sportswear': typeof SportswearRoute
  '/track': typeof TrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activewear': typeof ActivewearRoute
  '/casual-wear': typeof CasualWearRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/quote': typeof QuoteRoute
  '/sportswear': typeof SportswearRoute
  '/track': typeof TrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activewear': typeof ActivewearRoute
  '/casual-wear': typeof CasualWearRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/quote': typeof QuoteRoute
  '/sportswear': typeof SportswearRoute
  '/track': typeof TrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activewear'
    | '/casual-wear'
    | '/checkout'
    | '/contact'
    | '/quote'
    | '/sportswear'
    | '/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activewear'
    | '/casual-wear'
    | '/checkout'
    | '/contact'
    | '/quote'
    | '/sportswear'
    | '/track'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activewear'
    | '/casual-wear'
    | '/checkout'
    | '/contact'
    | '/quote'
    | '/sportswear'
    | '/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivewearRoute: typeof ActivewearRoute
  CasualWearRoute: typeof CasualWearRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  QuoteRoute: typeof QuoteRoute
  SportswearRoute: typeof SportswearRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activewear': {
      id: '/activewear'
      path: '/activewear'
      fullPath: '/activewear'
      preLoaderRoute: typeof ActivewearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casual-wear': {
      id: '/casual-wear'
      path: '/casual-wear'
      fullPath: '/casual-wear'
      preLoaderRoute: typeof CasualWearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportswear': {
      id: '/sportswear'
      path: '/sportswear'
      fullPath: '/sportswear'
      preLoaderRoute: typeof SportswearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivewearRoute: ActivewearRoute,
  CasualWearRoute: CasualWearRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  QuoteRoute: QuoteRoute,
  SportswearRoute: SportswearRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
